{"name": "test_01_login", "status": "broken", "statusDetails": {"message": "AttributeError: type object 'Test_Login_Vue' has no attribute 'log'", "trace": "self = <class 'TestCase.test_vue.Test_Login_Vue'>\n\n    def setup_class(self) -> None:\n>       self.log.info(\"======打开浏览器======\")  # 加入log\nE       AttributeError: type object 'Test_Login_Vue' has no attribute 'log'\n\nTestCase/test_vue.py:22: AttributeError"}, "start": 1647428595468, "stop": 1647428595468, "uuid": "012eac5f-0db9-4a0b-8a1d-f8c8480dec35", "historyId": "3ac5a797f6e4915dedbb644a3353598a", "testCaseId": "1d4a513abf8f7571f28accd346971ab3", "fullName": "TestCase.test_vue.Test_Login_Vue#test_01_login", "labels": [{"name": "parentSuite", "value": "TestCase"}, {"name": "suite", "value": "test_vue"}, {"name": "subSuite", "value": "Test_Login_Vue"}, {"name": "host", "value": "YZQ.local"}, {"name": "thread", "value": "34349-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "TestCase.test_vue"}]}