{"uuid": "7e5333cb-c42a-465b-8f17-9bce5c46edd7", "children": ["520584e3-f8d3-461a-9093-5a621197aa78", "3d9fd6f7-493c-47bf-9349-1747f8b21090", "618d53e2-0177-4d5e-a9e7-d9ab70e5fcd8"], "befores": [{"name": "_Class__pytest_setup_class", "status": "passed", "start": 1647339633167, "stop": 1647339635015}], "afters": [{"name": "_Class__pytest_setup_class::0", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.NoSuchWindowException: Message: no such window: target window already closed\nfrom unknown error: web view not found\n  (Session info: chrome=99.0.4844.51)\nStacktrace:\n0   chromedriver                        0x000000010c180159 chromedriver + 5120345\n1   chromedriver                        0x000000010c10db13 chromedriver + 4651795\n2   chromedriver                        0x000000010bcfde68 chromedriver + 392808\n3   chromedriver                        0x000000010bcde18c chromedriver + 262540\n4   chromedriver                        0x000000010bd540cb chromedriver + 745675\n5   chromedriver                        0x000000010bd58530 chromedriver + 763184\n6   chromedriver                        0x000000010bd50b08 chromedriver + 731912\n7   chromedriver                        0x000000010bd265dd chromedriver + 558557\n8   chromedriver                        0x000000010bd274f5 chromedriver + 562421\n9   chromedriver                        0x000000010c13d38d chromedriver + 4846477\n10  chromedriver                        0x000000010c15721c chromedriver + 4952604\n11  chromedriver                        0x000000010c15ca12 chromedriver + 4975122\n12  chromedriver                        0x000000010c157b4a chromedriver + 4954954\n13  chromedriver                        0x000000010c1325b0 chromedriver + 4801968\n14  chromedriver                        0x000000010c171f78 chromedriver + 5062520\n15  chromedriver                        0x000000010c1720ff chromedriver + 5062911\n16  chromedriver                        0x000000010c187545 chromedriver + 5150021\n17  libsystem_pthread.dylib             0x00007fff2030f8fc _pthread_start + 224\n18  libsystem_pthread.dylib             0x00007fff2030b443 thread_start + 15\n\n", "trace": "  File \"/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/allure_commons/_allure.py\", line 200, in __call__\n    return self._fixture_function(*args, **kwargs)\n  File \"/Users/yangzhiqi/PycharmProjects/Selenium/venv/lib/python3.9/site-packages/_pytest/fixtures.py\", line 800, in _teardown_yield_fixture\n    next(it)\n  File \"/Users/yangzhiqi/PycharmProjects/Selenium/venv/lib/python3.9/site-packages/_pytest/python.py\", line 705, in xunit_setup_class_fixture\n    _call_with_optional_argument(func, self.obj)\n  File \"/Users/yangzhiqi/PycharmProjects/Selenium/venv/lib/python3.9/site-packages/_pytest/python.py\", line 632, in _call_with_optional_argument\n    func(arg)\n  File \"/Users/yangzhiqi/PycharmProjects/Selenium/TestCase/test_vue.py\", line 45, in teardown_class\n    self.driver.close()\n  File \"/Users/yangzhiqi/PycharmProjects/Selenium/venv/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py\", line 938, in close\n    self.execute(Command.CLOSE)\n  File \"/Users/yangzhiqi/PycharmProjects/Selenium/venv/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py\", line 425, in execute\n    self.error_handler.check_response(response)\n  File \"/Users/yangzhiqi/PycharmProjects/Selenium/venv/lib/python3.9/site-packages/selenium/webdriver/remote/errorhandler.py\", line 247, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1647339692068, "stop": 1647339694075}], "start": 1647339633167, "stop": 1647339694075}