{"uuid": "ece51c44-36c6-425d-85c0-f650ae021ee9", "children": ["e98cd946-a8e2-4597-93cf-6298f2eec4e5", "91084474-5f8e-4fd3-b51d-d17dd6d06c27", "1740bbaa-097b-4c69-9988-78daab8d8950", "3f15e904-eddd-432a-943b-1ed86abe6064", "511e29f1-6c77-4d83-bb95-9b2f7e3a35a6"], "befores": [{"name": "_Class__pytest_setup_class", "status": "passed", "start": 1647309349526, "stop": 1647309351402}], "afters": [{"name": "_Class__pytest_setup_class::0", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.NoSuchWindowException: Message: no such window: target window already closed\nfrom unknown error: web view not found\n  (Session info: chrome=99.0.4844.51)\nStacktrace:\n0   chromedriver                        0x00000001090dfee9 chromedriver + 5013225\n1   chromedriver                        0x000000010906b1d3 chromedriver + 4534739\n2   chromedriver                        0x0000000108c41a68 chromedriver + 170600\n3   chromedriver                        0x0000000108c2310e chromedriver + 45326\n4   chromedriver                        0x0000000108c96dbc chromedriver + 519612\n5   chromedriver                        0x0000000108c9b15e chromedriver + 536926\n6   chromedriver                        0x0000000108c937a8 chromedriver + 505768\n7   chromedriver                        0x0000000108c6976e chromedriver + 333678\n8   chromedriver                        0x0000000108c6a745 chromedriver + 337733\n9   chromedriver                        0x000000010909befe chromedriver + 4734718\n10  chromedriver                        0x00000001090b5a19 chromedriver + 4839961\n11  chromedriver                        0x00000001090bb1c8 chromedriver + 4862408\n12  chromedriver                        0x00000001090b63aa chromedriver + 4842410\n13  chromedriver                        0x0000000109090a01 chromedriver + 4688385\n14  chromedriver                        0x00000001090d1538 chromedriver + 4953400\n15  chromedriver                        0x00000001090d16c1 chromedriver + 4953793\n16  chromedriver                        0x00000001090e7225 chromedriver + 5042725\n17  libsystem_pthread.dylib             0x00007fff2030f8fc _pthread_start + 224\n18  libsystem_pthread.dylib             0x00007fff2030b443 thread_start + 15\n\n", "trace": "  File \"/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/allure_commons/_allure.py\", line 200, in __call__\n    return self._fixture_function(*args, **kwargs)\n  File \"/Users/yangzhiqi/PycharmProjects/Selenium/venv/lib/python3.9/site-packages/_pytest/fixtures.py\", line 800, in _teardown_yield_fixture\n    next(it)\n  File \"/Users/yangzhiqi/PycharmProjects/Selenium/venv/lib/python3.9/site-packages/_pytest/python.py\", line 705, in xunit_setup_class_fixture\n    _call_with_optional_argument(func, self.obj)\n  File \"/Users/yangzhiqi/PycharmProjects/Selenium/venv/lib/python3.9/site-packages/_pytest/python.py\", line 632, in _call_with_optional_argument\n    func(arg)\n  File \"/Users/yangzhiqi/PycharmProjects/Selenium/TestCase/test_vue.py\", line 51, in teardown_class\n    self.driver.close()\n  File \"/Users/yangzhiqi/PycharmProjects/Selenium/venv/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py\", line 938, in close\n    self.execute(Command.CLOSE)\n  File \"/Users/yangzhiqi/PycharmProjects/Selenium/venv/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py\", line 425, in execute\n    self.error_handler.check_response(response)\n  File \"/Users/yangzhiqi/PycharmProjects/Selenium/venv/lib/python3.9/site-packages/selenium/webdriver/remote/errorhandler.py\", line 247, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1647309360716, "stop": 1647309362728}], "start": 1647309349526, "stop": 1647309362728}