{"uuid": "76ca6033-9585-4d52-8779-000bad28d350", "children": ["939c5d0d-bce3-4a52-a652-80dd3e2a5bd2", "4f7d36fe-48b2-4c06-b25a-94327c53d4f9", "4728ac7a-db1d-4e66-a729-a34987a645a6"], "befores": [{"name": "_Class__pytest_setup_class", "status": "passed", "start": 1647339433216, "stop": 1647339435031}], "afters": [{"name": "_Class__pytest_setup_class::0", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.NoSuchWindowException: Message: no such window: target window already closed\nfrom unknown error: web view not found\n  (Session info: chrome=99.0.4844.51)\nStacktrace:\n0   chromedriver                        0x000000010c9ca159 chromedriver + 5120345\n1   chromedriver                        0x000000010c957b13 chromedriver + 4651795\n2   chromedriver                        0x000000010c547e68 chromedriver + 392808\n3   chromedriver                        0x000000010c52818c chromedriver + 262540\n4   chromedriver                        0x000000010c59e0cb chromedriver + 745675\n5   chromedriver                        0x000000010c5a2530 chromedriver + 763184\n6   chromedriver                        0x000000010c59ab08 chromedriver + 731912\n7   chromedriver                        0x000000010c5705dd chromedriver + 558557\n8   chromedriver                        0x000000010c5714f5 chromedriver + 562421\n9   chromedriver                        0x000000010c98738d chromedriver + 4846477\n10  chromedriver                        0x000000010c9a121c chromedriver + 4952604\n11  chromedriver                        0x000000010c9a6a12 chromedriver + 4975122\n12  chromedriver                        0x000000010c9a1b4a chromedriver + 4954954\n13  chromedriver                        0x000000010c97c5b0 chromedriver + 4801968\n14  chromedriver                        0x000000010c9bbf78 chromedriver + 5062520\n15  chromedriver                        0x000000010c9bc0ff chromedriver + 5062911\n16  chromedriver                        0x000000010c9d1545 chromedriver + 5150021\n17  libsystem_pthread.dylib             0x00007fff2030f8fc _pthread_start + 224\n18  libsystem_pthread.dylib             0x00007fff2030b443 thread_start + 15\n\n", "trace": "  File \"/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/allure_commons/_allure.py\", line 200, in __call__\n    return self._fixture_function(*args, **kwargs)\n  File \"/Users/yangzhiqi/PycharmProjects/Selenium/venv/lib/python3.9/site-packages/_pytest/fixtures.py\", line 800, in _teardown_yield_fixture\n    next(it)\n  File \"/Users/yangzhiqi/PycharmProjects/Selenium/venv/lib/python3.9/site-packages/_pytest/python.py\", line 705, in xunit_setup_class_fixture\n    _call_with_optional_argument(func, self.obj)\n  File \"/Users/yangzhiqi/PycharmProjects/Selenium/venv/lib/python3.9/site-packages/_pytest/python.py\", line 632, in _call_with_optional_argument\n    func(arg)\n  File \"/Users/yangzhiqi/PycharmProjects/Selenium/TestCase/test_vue.py\", line 45, in teardown_class\n    self.driver.close()\n  File \"/Users/yangzhiqi/PycharmProjects/Selenium/venv/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py\", line 938, in close\n    self.execute(Command.CLOSE)\n  File \"/Users/yangzhiqi/PycharmProjects/Selenium/venv/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py\", line 425, in execute\n    self.error_handler.check_response(response)\n  File \"/Users/yangzhiqi/PycharmProjects/Selenium/venv/lib/python3.9/site-packages/selenium/webdriver/remote/errorhandler.py\", line 247, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1647339491592, "stop": 1647339493600}], "start": 1647339433216, "stop": 1647339493600}