{"uuid": "6c815ec1-d815-431a-88e9-5f47ccbfaaa5", "children": ["fd3b55a3-476d-400d-bb4e-a6ef33666218", "e4a34fbc-7eb6-4b15-95fb-89284c32fcd7", "39867379-8776-4884-8e46-dc647df43e29"], "befores": [{"name": "_Class__pytest_setup_class", "status": "passed", "start": 1647340603307, "stop": 1647340605445}], "afters": [{"name": "_Class__pytest_setup_class::0", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.NoSuchWindowException: Message: no such window: target window already closed\nfrom unknown error: web view not found\n  (Session info: chrome=99.0.4844.51)\nStacktrace:\n0   chromedriver                        0x0000000105051159 chromedriver + 5120345\n1   chromedriver                        0x0000000104fdeb13 chromedriver + 4651795\n2   chromedriver                        0x0000000104bcee68 chromedriver + 392808\n3   chromedriver                        0x0000000104baf18c chromedriver + 262540\n4   chromedriver                        0x0000000104c250cb chromedriver + 745675\n5   chromedriver                        0x0000000104c29530 chromedriver + 763184\n6   chromedriver                        0x0000000104c21b08 chromedriver + 731912\n7   chromedriver                        0x0000000104bf75dd chromedriver + 558557\n8   chromedriver                        0x0000000104bf84f5 chromedriver + 562421\n9   chromedriver                        0x000000010500e38d chromedriver + 4846477\n10  chromedriver                        0x000000010502821c chromedriver + 4952604\n11  chromedriver                        0x000000010502da12 chromedriver + 4975122\n12  chromedriver                        0x0000000105028b4a chromedriver + 4954954\n13  chromedriver                        0x00000001050035b0 chromedriver + 4801968\n14  chromedriver                        0x0000000105042f78 chromedriver + 5062520\n15  chromedriver                        0x00000001050430ff chromedriver + 5062911\n16  chromedriver                        0x0000000105058545 chromedriver + 5150021\n17  libsystem_pthread.dylib             0x00007fff2030f8fc _pthread_start + 224\n18  libsystem_pthread.dylib             0x00007fff2030b443 thread_start + 15\n\n", "trace": "  File \"/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/allure_commons/_allure.py\", line 200, in __call__\n    return self._fixture_function(*args, **kwargs)\n  File \"/Users/yangzhiqi/PycharmProjects/Selenium/venv/lib/python3.9/site-packages/_pytest/fixtures.py\", line 800, in _teardown_yield_fixture\n    next(it)\n  File \"/Users/yangzhiqi/PycharmProjects/Selenium/venv/lib/python3.9/site-packages/_pytest/python.py\", line 705, in xunit_setup_class_fixture\n    _call_with_optional_argument(func, self.obj)\n  File \"/Users/yangzhiqi/PycharmProjects/Selenium/venv/lib/python3.9/site-packages/_pytest/python.py\", line 632, in _call_with_optional_argument\n    func(arg)\n  File \"/Users/yangzhiqi/PycharmProjects/Selenium/TestCase/test_vue.py\", line 54, in teardown_class\n    self.driver.close()\n  File \"/Users/yangzhiqi/PycharmProjects/Selenium/venv/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py\", line 938, in close\n    self.execute(Command.CLOSE)\n  File \"/Users/yangzhiqi/PycharmProjects/Selenium/venv/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py\", line 425, in execute\n    self.error_handler.check_response(response)\n  File \"/Users/yangzhiqi/PycharmProjects/Selenium/venv/lib/python3.9/site-packages/selenium/webdriver/remote/errorhandler.py\", line 247, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1647340615860, "stop": 1647340617872}], "start": 1647340603307, "stop": 1647340617872}